### ISSUE TITLE
Display the page where the global style kit was updated on.

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#102]
Would it be possible somehow to display the page from which the Global style kit was saved from? This is the page where usually confusions happen regarding updating the style kit, but there is no way to remember the page always.
![Screenshot 2019-05-19 at 22 20 08](https://user-images.githubusercontent.com/4193672/57986975-4a294080-7a84-11e9-87e1-56358b0f923b.png)

**Comment by mauryaratan** [comment]
> now that we have the Stylekit update detected thing, it is not needed.

As @JohnPixle [suggested](https://codestag.slack.com/archives/CEZU5M8G7/p1563264451005900), this isn't needed any longer.
