### ISSUE TITLE
Force CSS Regeneration after a Global Style Kit has been Updated, Assigned or Unassigned.

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#103]
We talked about this in the client project. This is very very confusing. Here is the breakdown:

1. You work with a global stylekit
2. you make some style changes, and you update the stylekit
3. Other pages that have the global stylekit applied do not get updated with the latest changes unless the user resets the current stylekit, and re-apply it from the dropdown in the page styles panel.

This is currently the biggest flaw we have I believe, because it will break users expectations and will create confusion with the styles. Elementor has already countless issues with caching and css, let's make our best to blend in seamlessly.

**Comment by mauryaratan** [comment]
Fixed in e02aebb9f13547f3e5d3aef3b9a6e6b1488bceb2.
