### ISSUE TITLE
Add a custom field at templates in template gallery

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#112]
Can we use a toggle or checkbox to each of the templates in our gallery, where we define if the template has a stylekit assigned? We need this because ideally we want to display the popup everytime a user imports one of these templates, so they can get an idea of how things work.

<img width="863" alt="Screenshot 2019-06-14 at 11 03 35" src="https://user-images.githubusercontent.com/4193672/59493711-22b37100-8e94-11e9-9411-0c079cec9c18.png">

**Comment by mauryaratan** [comment]
Added.
