### ISSUE TITLE
Primary accent to apply on FA icons by default

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#130]
By default, when you drop an icon element, or an icon box into the layout, you get this blunt gray color. Would it make sense to apply the Primary accent to it? I think it would make sense.

![Screenshot 2019-08-16 at 11 56 12](https://user-images.githubusercontent.com/4193672/63156238-eed40380-c01c-11e9-83f0-222cea3664fc.png)

**Comment by mauryaratan** [comment]
I'm not too sure about this @JohnPixle, we can probably go for it given the user will still be able to override the colors internally with Icon's respective styling.

I wonder if there are other Elements which can profit from this as well. Can we look for such similar elements?

**Comment by JohnPixle** [comment]
Users can override for sure. It simply makes sense to have a consistent color on the elements that you drop in the editor by default.

There are many elements that we can apply this technique.

As mentioned, it's Icon box widget, icon widget, and we can look for other elements for the future.

**Comment by JohnPixle** [comment]
Hm, also it might be the progress bar for example @mauryaratan .

![Screenshot 2019-08-16 at 13 20 36](https://user-images.githubusercontent.com/4193672/63161390-af131900-c028-11e9-86ab-e3f52699d945.png)

**Comment by medvedbne** [comment]
Perhaps to add it to the dividers too?

**Comment by JohnPixle** [comment]
> Perhaps to add it to the dividers too?
We are exploring this option for the upcoming update!

**Comment by JohnPixle** [comment]
I think we must definitely revisit this, it's a struggle in the workflow.
The accent color is applied on the icons in the icon boxes and icon lists, why not at the Icon elements?

@lushkant Let me know your thought on this
