### ISSUE TITLE
Style Kit imported popup

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#137]
After a Style Kit has been imported, we should offer the user a hint, like this popup.

![Screenshot 2019-08-21 at 11 14 22](https://user-images.githubusercontent.com/4193672/63414592-d9881c00-c404-11e9-8222-16f95a0bf1e1.png)

https://www.figma.com/file/WewTsQAjGvzRQahddcH0KK6m/Product-UI?node-id=461%3A0

**Comment by JohnPixle** [comment]
We need this to avoid confusion in the case that users think that by importing a Style Kit it is applied on the page automatically.

**Comment by mauryaratan** [comment]
@JohnPixle I'm not sure I quite get this, I assume this is for Elementor screen? When should it be triggered?
