### ISSUE TITLE
Style Kit selection dropdown in quick view and bulk edit panels

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#139]
It would mean a great deal to users if we could bulk manage the Style Kits that are applied on the page. How about we add a Style Kit select dropdown to the Quick View and Bulk Edit?

This way I can apply Stylekits to a number of pages without the need to go through them one by one.

![Screenshot 2019-08-21 at 13 10 32](https://user-images.githubusercontent.com/4193672/63423500-1d831d00-c415-11e9-8ad7-f79bc531787a.png)

![Screenshot 2019-08-21 at 13 13 44](https://user-images.githubusercontent.com/4193672/63423724-98e4ce80-c415-11e9-89c4-3757e6a1996d.png)

**Comment by mauryaratan** [comment]
Fixed in 677d9722ee9235b832fc2bbbfc3179d1dce0fa4c.
