### ISSUE TITLE
Add Docs links to SK panels

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#140]
Given the fact that there has been some work done at the docs, I think it would be a good idea to add helper links to some of the panels, following this example:

![Screenshot 2019-08-21 at 13 59 56](https://user-images.githubusercontent.com/4193672/63426628-fb40cd80-c41b-11e9-8b28-fb974d389960.png)

**Colors:** 
Set the colors for Typography, accents and more. Learn more about colors _here_
link: https://docs.analogwp.com/article/574-working-with-colours

**Heading Sizes:** 
Tweak the size of your Heading elements using these presets. Learn more about Heading Sizes _here_
link: https://docs.analogwp.com/article/575-text-and-heading-sizes

**Text Sizes**
Tweak the size of text elements using these presets. Learn more about Text Sizes _here_
link: https://docs.analogwp.com/article/575-text-and-heading-sizes

**Buttons**
Define the default styles for every button size. Learn how to manage buttons _here_
link: https://docs.analogwp.com/article/586-button-styles-and-sizes

**Outer Section Padding**
Add padding to the outer sections of your layouts by using these controls. More details on Section padding _here_
link: https://docs.analogwp.com/article/587-outer-section-padding

**Column Gaps**
Column Gap presets add padding to the columns of a section. Find out how column gaps work _here_
link: https://docs.analogwp.com/article/588-working-with-column-gaps

**Comment by mauryaratan** [comment]
@JohnPixle Can you please ping when bottom 3 docs are complete as well?

**Comment by JohnPixle** [comment]
Ok @mauryaratan , I will do it today so we can have things ready for the update

**Comment by JohnPixle** [comment]
@mauryaratan These are done!
