### ISSUE TITLE
Style Kit name is not dynamically updated in the Quickview

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#141]
I accidentally discovered this at the work.analog site... 
Looks like the name here is not updated in the case that the Style Kit is renamed. There is No Poppins SK currently, it was renamed to something else, but the name remained here.

![Screenshot 2019-08-21 at 14 14 16](https://user-images.githubusercontent.com/4193672/63427578-1e6c7c80-c41e-11e9-85a6-215021984fba.png)

**Comment by mauryaratan** [comment]
@JohnPixle There must be some confusion here. I just tested this and it works fine as expected. If you're still having the issue though, can we please replicate it at play site?

**Comment by mauryaratan** [comment]
As it turns out, that badge is displayed even if the Style Kit is moved to trash. The ideal solution here is to show the badge only if it's published.

**Comment by JohnPixle** [comment]
Following the Slack conversation, it looks like the SK was deleted, yet the badge was still there. We decided to hide the badge if a SK is deleted
