### ISSUE TITLE
Conflict with Central Color Palette Plugin

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#149]
Got this message via FB PM today, definitely worth solving it. I would be among the first users who would value a close integration between those two.

> Unfortunately your Plugin does not work nicely with another very helpful plugin, Central Color Palette. CCP works fine with Elementor, but when Style Kits is active, the number of colors is reduced to 4. Style Kits and CCP would fit really nicely together. Would you please have a look?

**Comment by fabiolopeswp** [comment]
After running some tests I found out that the problem exists when SKs sync option is checked. Style Kits override CCP palette + Elementor palette. We must find a way of both plugins show the color palettes. 

When Sync is checked, the number of colors showed in the Color Picker is equal to the number of colors selected in the Global Color Panel of SKs. 

It can be from 1 to 6. 

This also means, that if we add a new Sks functionality that allows us to add as many colors as we want, this will practically remove the need of CCP.
