### ISSUE TITLE
💡 Implementing a 'column alignment fix' feature

### ISSUE THREAD

**Issue by sunnyt7** [mauryaratan/analogwp-templates#150]
One plugin that I use on my Elementor sites is called Columns Alignment Fix for Elementor (https://wordpress.org/…/columns-alignment-fix-for-elementor/). It basically just lets you use column gaps without messing up all your container alignments.

I'd love to see something like this integrated into Style Kits. The issue is right now if you change your column gap defaults, their plugin obviously doesn't adjust.

It outputs some basic CSS which is easy to adjust if you want to go in and modify the plugin, but it'd be awesome if Style Kits could take care of that automatically.

Since an integration is obviously not at all likely, this would essentially mean replicating their plugin as a feature within yours.

**Comment by JohnPixle** [comment]
I am closing this as we definitely align towards a less dependent direction. Thanks for the input!
