### ISSUE TITLE
Typography - Heading margins

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#153]
When users use Hello or any other theme that does not define margins for headings, we have a problem.
![Screenshot 2019-09-06 at 10 07 59](https://user-images.githubusercontent.com/4193672/64407968-51557800-d08e-11e9-9e20-1eec472f2a15.png)

We can perhaps add simple margin controls at the headings panel like this

![Screenshot 2019-09-06 at 10 17 36](https://user-images.githubusercontent.com/4193672/64408508-a219a080-d08f-11e9-825f-a4c595a65d50.png)

**Figma** 👉🏻 https://www.figma.com/file/WewTsQAjGvzRQahddcH0KK6m/Product-UI?node-id=503%3A3540

**Comment by mauryaratan** [comment]
Fixed in 147c5516.
