### ISSUE TITLE
SK - Button color [clear / default]  

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#156]
In the SK Buttons colors, check the "default" button, which is supposed to reset / clear the selected color. I think it does not work. Perhaps we can have this say "clear"? 

![Screenshot_2019-09-08_at_10 49 12](https://user-images.githubusercontent.com/4193672/64511191-71827280-d2ec-11e9-9d89-f1d37930bfa8.png)

**Comment by mauryaratan** [comment]
@JohnPixle This is fine actually.

When a color is supplied to a setting as default value, the button there always says *Default*. When no default value is provided, it'll fallback to *Clear* option.

In our case, any Style Kit value becomes a default value for those settings.
