### ISSUE TITLE
🔥  Better template import management

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#161]
I believe this must be one of our priorities for now, It is the first interaction with the user and an SK-powered template so we need to adapt this to a proper context.

👉🏻 comments on figma: https://www.figma.com/file/WewTsQAjGvzRQahddcH0KK6m/Product-UI?node-id=529%3A118

![Screenshot 2019-09-12 at 22 13 09](https://user-images.githubusercontent.com/4193672/64813707-a7ed1580-d5aa-11e9-87f8-6ca4240dbeee.png)

**Comment by JohnPixle** [comment]
This design is subject to change into this: 
![Screenshot 2019-09-16 at 13 21 23](https://user-images.githubusercontent.com/4193672/64950790-e7ef1980-d884-11e9-92bf-45477f6334b5.png)

**Comment by mauryaratan** [comment]
@JohnPixle a few questions?

- Should this modal be followed before importing a template or after?
- The bottom text saying *default import method*, what does it refer to?
- The SK dropdown seen in the screenshot, does it lists our library SKs are all SKs on a users' site.
- Lastly, we can probably drop this design and match existing or redo other popup modal as well.

Thanks.

**Comment by JohnPixle** [comment]
@mauryaratan 

1. Ideally, we do not want to display the layout without a stylekit applied on it, so i think it would be better to do it before.

2. It refers to a potential idea about having an option to set a default behavior in the settings. We can postpone this functionality as it is not needed in the MVP

![Screenshot 2019-09-18 at 16 32 23](https://user-images.githubusercontent.com/4193672/65153158-f0d11e00-da31-11e9-8ef1-8837aeb11b6b.png)

3. Both somehow if possible. If a template from our gallery is imported that has a style kit attached, , this Style Kit must be imported and applied on the template, if the user does not have it in his SK list.

4. I think we must decide a global style for the popups, i will revise this one a bit.
