### ISSUE TITLE
 ⚡️Provide more recent rollback version

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#162]
I think we can definitely keep this updated with the latest versions, especially after the recent fixes.

**Comment by mauryaratan** [comment]
Following the Elementor's pattern, I'm thinking of providing the ability to rollback to any version available from the WordPress.org repo, it basically lists all the [tags](https://plugins.trac.wordpress.org/browser/analogwp-templates/tags).

Let me know your thoughts @JohnPixle!

**Comment by JohnPixle** [comment]
@mauryaratan definitely agree with this, users might need to revert to a version with more recent features. Colors for example I say go with it.
