### ISSUE TITLE
⚠️ Conflicting span, p and div html tags in Heading element

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#163]

**Comment by JohnPixle** [comment]
This is a know issue, and it has been brought to the surface by users, the line-height controls are not work-able for the p and div HTML tags. They only work for the Span tag.

We definitely need to have those fixed as most of the times we need a p tag or a simple div.

**Comment by mauryaratan** [comment]
Hey @JohnPixle, probably doing something wrong here but couldn't replicate the issue. Here's what I tried:

- Add a heading widget
- Set the size to XXL
- Then from *Text Sizes* section I changed the font size/line-height
- Back to the Heading widget, I switched the HTML tag between div/p/span and the results were same.

Please let me know if it's different for you.

**Comment by JohnPixle** [comment]
Did a quick video to highlight the issue. https://www.loom.com/share/a44b13e10e624693b6a78db1f4c8d47f

You are right that the line-height responds from the Text sizes line-height control, but i dont think it works for the default size. I mean when you have not set a custom size to an element.

**Comment by mauryaratan** [comment]
@JohnPixle It's not supposed to work with default size? Our text sizes correspond to one of the selected values at Size dropdown, as defined in Text Sizes control XXL/XL/Large/Medium/Small.

For default size, do you think it should inherit the line-height set to body typography?
