### ISSUE TITLE
⚠️ The option for not applying link color on active titles is not saved on the stylekit

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#166]
This should be saved in the style kit. Currently you need to define it per page.

![Screenshot 2019-09-13 at 13 43 46](https://user-images.githubusercontent.com/4193672/64857202-8fbdda80-d62c-11e9-815d-8786b1501919.png)

**Comment by mauryaratan** [comment]
@JohnPixle I just tested this by updating an existing Style Kit and it saved well as it should have. Please double-check and let me know if the issue still exists. Preferably on play site?

**Comment by JohnPixle** [comment]
Tested on play, it gets saved indeed.
