### ISSUE TITLE
Color controls for buttons do not "clear"

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#168]
Looks like the same issue we had for the color controls not properly resetting 
https://github.com/mauryaratan/analogwp-templates/issues/156

**Comment by mauryaratan** [comment]
@JohnPixle Please check my comment in the issue: https://github.com/mauryaratan/analogwp-templates/issues/156#issuecomment-530307392

**Comment by JohnPixle** [comment]
Sorry for this, indeed. I am closing this as well.

**Comment by lushkant** [comment]
Tried replicating this issue, but works fine for me.
