### ISSUE TITLE
Better empty state for when no templates are found

### ISSUE THREAD

**Issue by mauryaratan** [mauryaratan/analogwp-templates#170]
I noticed a bug where entering random text in search box still results with list of all templates where it should be blank. What happened there was, I was mistakenly returning the original list if the search didn't match any results.

In addition to #169, let's add an empty state when no templates are found. This should work for no matching search results as well.

**Comment by JohnPixle** [comment]
I agree, we can go for something like this for now.

![Screenshot 2019-09-18 at 17 40 31](https://user-images.githubusercontent.com/4193672/65158645-74433d00-da3b-11e9-82f9-1cdf28c2a96a.png)


https://www.figma.com/file/WewTsQAjGvzRQahddcH0KK6m/Product-UI?node-id=541%3A2017
