### ISSUE TITLE
⚠️ 'Hide Title" control is being reset after saving/updating the global Style Kit.

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#171]
We have had some reports in FB and in Twitter.

> when I update and re-save a global style kit, all h1 titles hidden with the "Hide Title" toggle re-appear...

Turns out it is true, here is some more context
https://www.loom.com/share/be9fd8baed534bd88c4d1fdb2dad286e

**Comment by mauryaratan** [comment]
Fixed in 6be04f8a4d2b0557fda7d4f231912023f9f5ca9d
