### ISSUE TITLE
UI: replace blue hex color

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#172]
Since we are on it, in the plugin UI can we replace the #3152FF blue color with the purple #5C32B6 so we are a bit more consistent with the brand?
I believe that if you do a search and replace, we should be good.

![Screenshot 2019-09-18 at 17 43 58](https://user-images.githubusercontent.com/4193672/65159016-1cf19c80-da3c-11e9-9b35-4e703b09c57f.png)

Also, let's make the change to the  .elementor-add-analogwp-button color, what say?

![Screenshot 2019-09-18 at 17 50 33](https://user-images.githubusercontent.com/4193672/65159498-d6507200-da3c-11e9-80bc-18ceafb59001.png)

**Comment by mauryaratan** [comment]
Fixed in 91c66ae6c8432ece15370311e473247f0c393e21.
