### ISSUE TITLE
Template Collection UI

### ISSUE THREAD

**Issue by mauryaratan** [mauryaratan/analogwp-templates#176]
Hey @JohnPixle, since we're going to have Template Collection now. It's good time to have a UI which groups the templates from the same pack together. 

It can be simply be listed as *Collection Name* with a different thumbnail (probably a simple card stack effect?), upon clicking it will expand the list of all templates inside then we can continue as we normally do for rest of the templates.

Server Side:
For each template, we can have a dropdown simply saying *Collection* which will populate the results.

**Comment by JohnPixle** [comment]
I have started work on this at Figma: https://www.figma.com/file/WewTsQAjGvzRQahddcH0KK6m/Product-UI?node-id=549%3A8298

There are two frames.

![Screenshot 2019-09-23 at 13 13 18](https://user-images.githubusercontent.com/4193672/65418003-11b7bb80-de04-11e9-837d-580eca654a3b.png)

Let's continue the brainstorming on Slack or Figma.

**Comment by JohnPixle** [comment]
The Group By Pack toggle must be visible at al times. However the Filter / sort / search row applies only for Templates, so I have put those controls in a second row, that will be displayed only when the Group by packs is switched off.

**Comment by mauryaratan** [comment]
I'd like to propose a different approach here.

Instead of having them displayed as big, let's have them in the same size a template is displayed while making the thumbnail visually distinctive (the reason why I suggested a stacked effect). This way we don't break the UI flow.

Having the templates from the same template pack displayed normally feels a bit cluttered to me. We should just probably just group them by default.

Let me know your thoughts on these @JohnPixle.

**Comment by JohnPixle** [comment]
This is going this route: https://www.figma.com/file/WewTsQAjGvzRQahddcH0KK6m/Product-UI?node-id=553%3A6613
