### ISSUE TITLE
New Settings Page

### ISSUE THREAD

**Issue by mauryaratan** [mauryaratan/analogwp-templates#178]
Notes:

- Separate settings page
- Tabs should be able to be added from other plugins
- Add only fields types we need in our plugin, and not bloat by pulling in any framework
- Old settings are stored in `ang_options`, tweak settings save method to pull/use the same

Design: [Figma](https://www.figma.com/file/WewTsQAjGvzRQahddcH0KK6m/Product-UI?node-id=575%3A9173)

**Comment by lushkant** [comment]
I've the settings page & methods ready to use, we just need to now sanitize/improvise it for production and what not!

**Comment by mauryaratan** [comment]
Merged the respective PR #181 .
