### ISSUE TITLE
💡 Add release dates in the changelog

### ISSUE THREAD

**Issue by jflagarde** [mauryaratan/analogwp-templates#179]
In the changelog ([https://wordpress.org/plugins/analogwp-templates/#developers](https://wordpress.org/plugins/analogwp-templates/#developers)), it would be useful to have the release date of each version from now on. The date could be added either to the right of the version number or just below the version number with a text similar to: "Release date: October 1st 2019"

**Comment by lushkant** [comment]
Hey @jflagarde,  this definitely sounds like a good idea to have the release dates marked with changelog versioning, I'll forward this to the team.

**Comment by JohnPixle** [comment]
@mauryaratan I think we can do this, makes sense for project maintenance. Thanks @jflagarde

**Comment by mauryaratan** [comment]
@lushkant can you please take care of this? The date for most of the versions can be found at [releases](https://github.com/mauryaratan/analogwp-templates/releases) page.

For versions not tagged in the releases, switch to *Tags* tab in-branch dropdown on the main page and check the last commit date.

Please do it in this format: `= 1.x.x - April 01, 2020 =`

**Comment by lushkant** [comment]
Added a PR for the same. :)
https://github.com/mauryaratan/analogwp-templates/pull/183

**Comment by mauryaratan** [comment]
This is merged in develop, will be a part of 1.3.8. Thanks @jflagarde, @lushkant.
