### ISSUE TITLE
⚠️ Accordion Widget - Titles - Hard color style on the title does not override accent color

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#180]
This is the same as https://github.com/mauryaratan/analogwp-templates/issues/167

but this time for the Accordion element. Can you check and fix this for the tabs widget title as well please?

**Comment by mauryaratan** [comment]
Fixed in #185.

**Comment by JohnPixle** [comment]
This does not seem resolved guys. https://www.loom.com/share/82847a169c5d4fa6b7bde1e98740b78b
