### ISSUE TITLE
⚠️ Better styling for stacked and framed views of icons

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#187]
@lushkant  Like we did for the icon widget, we should take care of the stacked and framed views of the icon in the icon box widget. In both these cases the sk primary accent color must take effect.

**Comment by lushkant** [comment]
Included already though needed a fix, added in the previous PR for icon elements https://github.com/mauryaratan/analogwp-templates/pull/186

**Comment by mauryaratan** [comment]
Fixed in #186.
