### ISSUE TITLE
⚠️ Import management: SK to be selected by default

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#189]
AT the first screen , the SK must be auto-populated.

![Screenshot 2019-10-17 at 15 59 06](https://user-images.githubusercontent.com/4193672/67011688-c63db800-f0f8-11e9-8b3d-d7c83a93b7a4.png)

Also, in the dropdown, it must say **Defaul**t instead of import.

![Screenshot 2019-10-17 at 15 59 09](https://user-images.githubusercontent.com/4193672/67011872-0c931700-f0f9-11e9-9160-6eda29dcb234.png)

**Comment by mauryaratan** [comment]
Fixed in 0db1054e55d9d9e3db45641f1dfc0429a21ca461.
