### ISSUE TITLE
⚠️  Background elements are visible at Preview popup

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#190]
In the new UI, when you preview a layout, the banners from the gallery behind show up in the background.

![Screenshot 2019-10-17 at 16 17 07](https://user-images.githubusercontent.com/4193672/67012450-18cba400-f0fa-11e9-85e5-b7f86b18d6ba.png)

**Comment by mauryaratan** [comment]
Not anymore, probably was fixed while tweaking as part of #161.
