### ISSUE TITLE
⚠️ Add "Create new" button to Manage SK page

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#201]
I am pretty sure we had this, but we need to definitely have the Add new button in the CPT page.

As users suggested on FB, in one of the next versions we should make the SKs editable with elementor. So there will be high probability that someone will be starting a fresh Style Kit from this page.

![Screenshot 2019-10-24 at 15 20 38](https://user-images.githubusercontent.com/4193672/67486725-36a68500-f675-11e9-87ca-77f5ca337cd9.png)

**Comment by mauryaratan** [comment]
Pushing this to a future release,
We're storing SK data differently as compared to how Elementor does it. So simply re-enabling the editing button won't do the job here. There needs to be a 2-way migration from Elementor <> Tokens to make this work.

Probably something for v1.4.0.

**Comment by mauryaratan** [comment]
With the addition of #281, this is no longer required.
