### ISSUE TITLE
💡 SK Post type to be editable with Elementor

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#206]
Details to follow soon.

**Comment by JohnPixle** [comment]
As suggested in the FB community, the idea is to have the Style Kit Custom Post Type at the _Manage Style Kits_ tab in the dashboard editable with Elementor.

![Screenshot 2019-11-13 at 13 28 43](https://user-images.githubusercontent.com/4193672/68760004-87c4eb80-0619-11ea-9a1a-0a342bbd7e64.png)

Then, everything stays the same, apart from the ability to change SKs of course.
The reason why I am suggesting this is that it would help a lot the users to have a mental model for the SK. 

![Editable Style Kit](https://user-images.githubusercontent.com/4193672/68759918-4d5b4e80-0619-11ea-91ab-cc6d6e065ec7.jpg)

let me know your input @mauryaratan

**Comment by mauryaratan** [comment]
With the addition of #281, this is no longer required.
