### ISSUE TITLE
Conditional mapping of normal buttons to one of existing sizes

### ISSUE THREAD

**Issue by mauryaratan** [mauryaratan/analogwp-templates#221]
Recently, we came across normal buttons remaining unstyled as our controls in Elementor only customize the Elementor buttons specifically. While we also noticed that if may affect theme styles on button that still doesn't means we should let the buttons remain unstyled.

#### Here's what I propose:
A new option called **Inherit Button Styles** which will be a dropdown with following styles:
- Default (let theme styles take over)
- Rest of the button sizes: S / M / L etc...

This way we also won't have to make decision for users regarding which button size should be inherit on normal buttons.

Let me know your thoughts @JohnPixle! Thanks.

**Comment by JohnPixle** [comment]
@mauryaratan I like the idea, where would you see this new option / dropdown?
I do believe that this must be on the SK level, not settings. thoughts?

**Comment by mauryaratan** [comment]
This could go under Buttons panels, right before the buttons tab @JohnPixle

**Comment by JohnPixle** [comment]
I worked on the conditional mapping for buttons a bit, attaching a screenshot and link to [figma.](https://www.figma.com/file/WewTsQAjGvzRQahddcH0KK6m/Product-UI?node-id=868%3A7036)
I think it would make sense to choose the button after they have defined the Styles for each size, hence I suggest we put this in the end of the buttons panel. Let me know your thoughts @mauryaratan 

![Theme Buttons (1)](https://user-images.githubusercontent.com/4193672/68758501-978f0080-0616-11ea-95ae-d95b0fc98c72.jpg)

**Comment by mauryaratan** [comment]
With the addition of #281, this is no longer required.
