### ISSUE TITLE
Add a global link hover color

### ISSUE THREAD

**Issue by mauryaratan** [mauryaratan/analogwp-templates#232]
There's been an increased request to be able to change Link hover colors globally.

We probably need a different approach to apply base link/hover color.

**Comment by JohnPixle** [comment]
@mauryaratan Since we agreed to have the BG color classes on their own panel, we can do it like this, and add a primary accent hover:

![Screenshot 2020-01-07 at 12 51 33](https://user-images.githubusercontent.com/4193672/71890277-98db3600-314c-11ea-8ac7-f09f5888517b.png)

**Comment by mauryaratan** [comment]
With the addition of #281, this is no longer required.
