### ISSUE TITLE
Fix Style issues at Settings page

### ISSUE THREAD

**Issue by lushkant** [mauryaratan/analogwp-templates#233]
Global anchor styles at Settings page -
![image](https://user-images.githubusercontent.com/18240138/70427775-5f56d280-1a9b-11ea-9e40-1ac2127e2337.png)

And Checkbox label, description left padding being applied elsewhere as well.

**Comment by mauryaratan** [comment]
Not just links, but any part of our styles should be scoped with a parent class.
