### ISSUE TITLE
Issue with active Icon box widget 

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#242]
@mauryaratan I encountered this issue when I was setting up the profile pages at our site at https://analogwp.com/account/

👉🏻 The profile pages are based on the template, so if you want to check / tweak the icon boxes,  this is the template that you must edit: https://analogwp.com/wp-admin/post.php?post=617&action=elementor

It happens with icon boxes that are Linked, and it happens in the stacked view. Feel free to edit the template

In the editor, by default the icon active icon inherits the accent color, which results in the following

![Screenshot 2019-12-12 at 17 35 52](https://user-images.githubusercontent.com/4193672/70725953-f8892180-1d05-11ea-951e-71fac0bcead4.png)

Then, I can apply an inline style to make the icon color white. All good at the editor:

![Screenshot 2019-12-12 at 17 35 09](https://user-images.githubusercontent.com/4193672/70725836-c4adfc00-1d05-11ea-937d-5d8f84c85b3e.png)

In the frontend though, this inline style is not respected as you see.

**Comment by JohnPixle** [comment]
Note that the hover works fine for the above icons

**Comment by mauryaratan** [comment]
This was fixed previously in 0d510594383a4ff31377d7300bb890e5a4499a37.
