### ISSUE TITLE
Sections should be edited / previewed following the styles of the global Style Kit by default

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#253]
This is a bit important, we better discuss it live. The thing is that we definitely need to be able to edit and preview the Sections, based on the styles of the GSK. Even if we dont have the options to select the SK or edit the SK values, we must make sure that the Global Style  Kit affects the appearance of the section when the user is editing it.

![Screenshot 2020-01-06 at 22 48 18](https://user-images.githubusercontent.com/4193672/71847911-d4d3b400-30d6-11ea-8a91-5eb386998a86.png)

Example, try to [edit this page.](https://play.analogwp.com/wp-admin/post.php?post=1073&action=elementor)

You will see that that Styles are not applied. Can we make it so by default that the Global Style Kit is applied on the Section Edit screens?

Let's talk

**Comment by JohnPixle** [comment]
Having the GSK styles applied when editing sections is crucial for two reasons:

1. Many plugins that allow users to create custom post "blocks" for the post grids rely on Section-based layouts. Jet Engine, Elementor custom Posts, Anywhere Elementor do this thing exactly, and all are major workflow players.

So If you want to design a post box that will be repeated in the archive loop, you first design this in a Section. We need to inherit the GSK styles when editing these section blocks.

2. We are adding Blocks in our game, and we will be encouraging section-based workflows, we cant afford not to have the SK styles there.

Just to be clear, I am not talking about adding the SK controls, I just look for a trick / hack so that the GSK is auto-applied on the Section when the user is editing it (the section.)

When the user imports the section inside a page that has SK A applied on it, the section inherits the SK A (as it does now). But when user is editing the section itself, we want to be able to have a GSK fallback.

**Comment by mauryaratan** [comment]
Closing this issue as we're officially supporting Theme Style panels, which are only editable in a post, so any other template type shouldn't see TS panels.
