### ISSUE TITLE
Persistent Admin Notice Dismisses

### ISSUE THREAD

**Issue by lushkant** [mauryaratan/analogwp-templates#255]
Currently, there is no default or standard way of handling admin notices that can persist if one dismisses it. 
The most common ways to persist notices are either user meta or transients. If we wish to have something efficient we need to create something in place for handling all these notices.

**Comment by mauryaratan** [comment]
Yo @lushkant, try adding a notification now. Final notification is added by appending to `analog_admin_notices` filter. Let me know if anything doesn't make sense or if you have any feedback.

Define a function.
```php
public function get_test_notification() {
	return new Admin\Notice(
		'test-notice',
		[
			'content'         => 'This is a simple notice',
			'dismissible'     => true,
			'type'            => Admin\Notice::TYPE_WARNING,
			'active_callback' => function() {
				return current_user_can( 'manage_options' );
			},
		]
	);
}
```

Then pass it on from constructor or initiator.
```php
add_filter(
	'analog_admin_notices',
	function( $notices ) {
		$notices[] = $this->get_test_notification();
		return $notices;
	}
);
```
