### ISSUE TITLE
Update WordPress.org screenshots

### ISSUE THREAD

**Issue by mauryaratan** [mauryaratan/analogwp-templates#259]
Screenshots at WP repository are not up to date as per plugin design. Let's update the screenshots to match current designs.

Lets make sure to do so when we're close to releasing v1.5 (or even right after) so nothing gets left behind.

**Comment by JohnPixle** [comment]
We can do it as soon as we have the 1.5 ready to push, with the final panels. I will add the screenshots here.

![template_kits](https://user-images.githubusercontent.com/4193672/72133011-18554900-3389-11ea-8b2a-4fb35be6b5a4.png)
![import_to_library](https://user-images.githubusercontent.com/4193672/72133156-6cf8c400-3389-11ea-8b66-dedc9ff1fb26.png)

**Comment by lushkant** [comment]
Ohkay so ignore the above screenshots, as they're out of date. Latest ones are below. With each comment you can find the screenshots categorized.

**Comment by lushkant** [comment]
From SK Library

![1](https://user-images.githubusercontent.com/18240138/72506277-9ae97700-3867-11ea-8cbf-ada7faa92906.png)
![2](https://user-images.githubusercontent.com/18240138/72506278-9ae97700-3867-11ea-95a8-77bbd12cdcf9.png)
![3](https://user-images.githubusercontent.com/18240138/72506279-9b820d80-3867-11ea-914b-05d77b3b0004.png)
![4](https://user-images.githubusercontent.com/18240138/72506281-9b820d80-3867-11ea-97a2-7912373967d4.png)
![5](https://user-images.githubusercontent.com/18240138/72506283-9b820d80-3867-11ea-9512-0293b871ff2e.png)
![6](https://user-images.githubusercontent.com/18240138/72506286-9c1aa400-3867-11ea-9b34-9155889d2585.png)
![7](https://user-images.githubusercontent.com/18240138/72506288-9c1aa400-3867-11ea-8954-165e644ebf94.png)

**Comment by lushkant** [comment]
SK Panels -

![2](https://user-images.githubusercontent.com/18240138/72508306-7e4f3e00-386b-11ea-8e66-ff72abe5b548.png)
![3](https://user-images.githubusercontent.com/18240138/72508307-7e4f3e00-386b-11ea-8ac2-e5d2e2e1a919.png)
![4](https://user-images.githubusercontent.com/18240138/72508308-7e4f3e00-386b-11ea-9e8b-12778feaeddb.png)
![5](https://user-images.githubusercontent.com/18240138/72508309-7e4f3e00-386b-11ea-8d02-7fe4b31207a2.png)
![6](https://user-images.githubusercontent.com/18240138/72508310-7ee7d480-386b-11ea-869e-1bff7e65f50a.png)
![7](https://user-images.githubusercontent.com/18240138/72508311-7ee7d480-386b-11ea-8d73-447e702e1741.png)
![8](https://user-images.githubusercontent.com/18240138/72508315-7f806b00-386b-11ea-8cbe-98d910ca31bc.png)
![9](https://user-images.githubusercontent.com/18240138/72508317-7f806b00-386b-11ea-93ba-8ed30bffb6d7.png)
![10](https://user-images.githubusercontent.com/18240138/72508320-7f806b00-386b-11ea-8291-07e3b32eae89.png)
![11](https://user-images.githubusercontent.com/18240138/72508322-80190180-386b-11ea-8164-9e11b71b65f3.png)
![12](https://user-images.githubusercontent.com/18240138/72508323-80190180-386b-11ea-8fa8-3d97a323eaef.png)
![1](https://user-images.githubusercontent.com/18240138/72508324-80190180-386b-11ea-8cc3-5f952adb7959.png)

**Comment by lushkant** [comment]
Settings Page -

![1](https://user-images.githubusercontent.com/18240138/72510201-0256f500-386f-11ea-89b1-418cccf4d8fe.png)
![2](https://user-images.githubusercontent.com/18240138/72510202-02ef8b80-386f-11ea-8533-0937400ed99d.png)
![3](https://user-images.githubusercontent.com/18240138/72510203-02ef8b80-386f-11ea-9f7c-42ef886e87c7.png)
![4](https://user-images.githubusercontent.com/18240138/72510204-02ef8b80-386f-11ea-920e-a37f947614b9.png)
