### ISSUE TITLE
Add 1px border between block image and title

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#262]
To differentiate the screenshot and the title, can we add the 1px border between those two?
Color can be #DDDDDD

![Screenshot 2020-01-10 at 10 29 57](https://user-images.githubusercontent.com/4193672/72138066-a5ea6600-3394-11ea-9bc5-56d11299a2d4.png)

![Screenshot 2020-01-10 at 10 34 40](https://user-images.githubusercontent.com/4193672/72138141-d3cfaa80-3394-11ea-8673-97e880e668ab.png)

**Comment by lushkant** [comment]
And centerized images - 8aaa4647d2708e7fb4e13ad76fbe3b6275932069
