### ISSUE TITLE
class duplication

### ISSUE THREAD

**Issue by midoelhawy** [mauryaratan/analogwp-templates#275]
`PHP Fatal error:  Cannot use Elementor\User as User because the name is already in use in /home1/*****/public_html/wp-content/plugins/analogwp-templates/inc/class-quick-edit.php
`

I found this error when I installed the plugin on an Webisite Created by  Elementor Plugin

**Comment by mauryaratan** [comment]
@midoelhawy Thanks for letting us know. Weird that we haven't seen the conflict during our test or even now at production. Is it possible for you to provide full error stack?

**Comment by lushkant** [comment]
@midoelhawy Although we couldn't replicate your issue above, but we have taken care of the condition where this may create a conflict and added a fix regarding the same. You'll get this patch when the next update gets pushed :)
