### ISSUE TITLE
Gallery Popup - Sorting does not work

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#278]
Hiya, I just published the Volt / car template kit in the gallery, all good.

I noticed that at the template popup, the sorting dropdowns do not seem to work. Ideally, we want the template kits to appear by latest by default, now the newest appears last.

![Screenshot 2020-01-19 at 22 42 07](https://user-images.githubusercontent.com/4193672/72688466-33a22000-3b10-11ea-8bb8-e415a3452c5e.png)

Also, we need to adjust the template kit preview window, part of the "new" labels appear at the top.

![Screenshot 2020-01-19 at 22 49 38](https://user-images.githubusercontent.com/4193672/72688327-a4483d00-3b0e-11ea-8832-a059d3aa5e96.png)

**Comment by mauryaratan** [comment]
Fixed in f3185fd92d77df6f29f5d0c829afb0848316a7a2.

Ignore Kits order, as they're defined in the custom ordering at backend.
