### ISSUE TITLE
Page Custom CSS and Style Kit

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#285]
The fact that the Page custom CSS is saved on the style kit, raises a number of issues. Some users on the EL Github liked the feature, but others got confused.

What we can do?

### Option A - Make this Optional
![Screenshot 2020-01-23 at 12 51 21](https://user-images.githubusercontent.com/4193672/72978601-6cc3e400-3ddf-11ea-9f81-4edb3632c545.png)
We can have this control optional. If users disable this, then the information is not saved on the style kit. I feel this is a bit tricky.

### Option B - Add a dedicated panel in SK 
This essentially is a dedicated place to add the custom CSS to the style kit. We can have this tab under the tools at the end.

![Screenshot 2020-01-23 at 12 51 34](https://user-images.githubusercontent.com/4193672/72978775-b90f2400-3ddf-11ea-9766-901b9611097a.png)

**Comment by mauryaratan** [comment]
With the addition of #281, this is no longer required.

CSS was stored as part of the page settings which was saved in Style Kit. Going ahead, we won't be saving custom CSS as part of Kits. Unless going ahead Elementor decides to add a custom CSS panel.
