### ISSUE TITLE
Put back toggle for "show Pro templates"

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#303]
We decided to put back the PRO / Free Filter **in the free version.** It is a bit too much for the users to see the Pro layouts by default. Let's get in back in for the free version.

![Screenshot 2020-01-31 at 10 21 35](https://user-images.githubusercontent.com/4193672/73523424-8a163500-4413-11ea-92f5-86373d9978b8.png)

**Comment by mauryaratan** [comment]
Note that all items should be visible by default.
