### ISSUE TITLE
Improve importing indicator

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#307]
As suggested in Beta feedback, the current loading graphic is barely noticeable. 
I think it would make a huge sense in UX to replace this with a simple loading bar like this.

![Screenshot 2020-01-31 at 12 26 51](https://user-images.githubusercontent.com/4193672/73532272-082f0780-4425-11ea-9ac8-1c83f93f2023.png)

We need to replace this when importing templates and Style Kits. (editor and wp dashboard view)

[FIGMA](https://www.figma.com/file/WewTsQAjGvzRQahddcH0KK6m/Product-UI?node-id=1031%3A8687)

**Comment by mauryaratan** [comment]
Requesting changes here @JohnPixle. Our importer returns data at once, so the progress bar isn't usable at all here. Instead, we need some sort of spinner or animated loading icon. That's the reason why we had the fading icon in the first place.

**Comment by JohnPixle** [comment]
Update for the record, we decided to go with these: https://loading.io/css/

![Screenshot 2020-01-31 at 12 36 18](https://user-images.githubusercontent.com/4193672/73533254-0a926100-4427-11ea-8c74-93586ec85e3e.png)
Dots with our accent color #7B48F9
