### ISSUE TITLE
Fatal Error since 1.5.4

### ISSUE THREAD

**Issue by thomasmalley** [mauryaratan/analogwp-templates#319]
After updating from 1.5.2 to 1.5.4 we got the following WordPress error message a couple of times:

> Fatal error: Uncaught Error: Call to undefined method ElementorExtras\Modules\Navigation\Widgets\Offcanvas::get_main_id() in /html/wordpress/wp-content/plugins/analogwp-templates/inc/elementor/class-typography.php:174 Stack trace: #0 /html/wordpress/wp-includes/class-wp-hook.php(290): Analog\Elementor\Typography->register_heading_typography(Object(ElementorExtras\Modules\Navigation\Widgets\Offcanvas), 'section_page_st...') #1 /html/wordpress/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array) #2 /html/wordpress/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /html/wordpress/wp-content/plugins/elementor/includes/base/controls-stack.php(1466): do_action('elementor/eleme...', Object(ElementorExtras\Modules\Navigation\Widgets\Offcanvas), 'section_page_st...', Array) #4 /html/wordpress/wp-content/plugins/elementor-extras/modules/navigation/widgets/offcanvas.php(1057): Elementor\Controls_Stack->end_controls_section() #5 /html/wordpress/wp-content/plugins/elementor-extras/modules/navigation/widgets/ in /html/wordpress/wp-content/plugins/analogwp-templates/inc/elementor/class-typography.php on line 174

We use the Plugin [Elementor Extras](https://shop.namogo.com/product/elementor-extras/) as well. But I can't quite see which plugin leads to the error

Please delete this Issue if its irrelevant 
Thank You! 🙏🏻

Best regards

**Comment by mauryaratan** [comment]
Thanks for letting us know @thomasmalley. It's happening due to a recent change, although the issue shouldn't be occurring at all, since the undefined method seen in error stack above, should've worked given that's Elementor core method.

Still, I'd add some extra conditional and workaround a way to avoid the issue.

**Comment by mauryaratan** [comment]
Hey @thomasmalley, just letting you know quickly that we've fixed the issue and deployed an update. Thanks again!

**Comment by thomasmalley** [comment]
Wow, that was quick :) 
Thanks to You!
