### ISSUE TITLE
Revise notification when Elementor is not activated

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#327]
We should say Style Kits instead of Analog templates

![Screenshot 2020-02-12 at 10 16 31](https://user-images.githubusercontent.com/4193672/74315765-d0a75000-4d80-11ea-98fd-2ea78da69b22.png)

**Comment by lushkant** [comment]
It's been fixed already so I'm taking this down, with a sweet comment. 🙂
