### ISSUE TITLE
Screen after update (Existing SK users with Elementor > 2.9)

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#332]
We are going to use this as a template for onboarding all users in the future.
This page here, will specifically appear when **existing SK users** update to the latest Style Kits version, with integration to Theme Styles.

[Figma Board.](https://www.figma.com/file/WewTsQAjGvzRQahddcH0KK6m/Product-UI?node-id=1124%3A9169)

![Screenshot 2020-02-17 at 14 25 00](https://user-images.githubusercontent.com/4193672/74654122-469d2400-5192-11ea-8b52-57e94ed39cf6.png)

**Comment by mauryaratan** [comment]
@lushkant Some notes:

- The same screen will be used for onboarding, so make sure the code can be extended.
- Video can be a simple embed. You can use either `$wp_embed->autoembed` with YT link or an iframe.
- User should be redirected to this screen, only if the following requirements are met:
  - User is using v1.6.0 or higher
  - User has 1 or more Style Kits (not Kits), fetch posts count `ang_tokens` CPT
  - And if `ang_kits_migrated` is not set to true.
