### ISSUE TITLE
Extra menu icons

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#340]
There is this strange behaviour with extra menu icons. They are visible only at the frontend. It seems that the number of extra icons depends on the number of style Kits available

This is only visible on frontend

![Screenshot 2020-02-19 at 12 27 57](https://user-images.githubusercontent.com/4193672/74826277-fb128380-5313-11ea-8c1e-ed070d2e0312.png)

**Comment by lushkant** [comment]
Though when I took a look at Elementor editor screen at preview site pages, it even showed up at there as well. Odd behavior yet again and not consistent for replication. 😕
