### ISSUE TITLE
Pages: Apply GSK shows even when the GSK is assigned on the page

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#345]
Even when the GSK is applied on the page, in Quick View I see the Apply GSK link. [Try it here.](https://preview.analogwp.com/dash/wp-admin/edit.php?post_type=page)

![Screenshot 2020-02-19 at 13 09 42](https://user-images.githubusercontent.com/4193672/74829199-2a77bf00-5319-11ea-83c2-eb49dc6a2c26.png)
![Screenshot 2020-02-19 at 13 09 35](https://user-images.githubusercontent.com/4193672/74829202-2ba8ec00-5319-11ea-9c1d-4d6b7b9ba416.png)

**Comment by lushkant** [comment]
I tried replicating this with el 2.9.2 and Sk 1.6.0 beta but the behavior works alright, also tried a migration from 1.5.6 to 1.6.0 with old sk's but the behavior is still working so it's pretty odd. 
The code for checking this at Apply GSK action link is also seems right so far not sure how it's being shown up at preview. 😕
