### ISSUE TITLE
Register Reset function in the revisions panel

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#353]
We need to be consistent with what the popup says, and register this as an action that can be reverted in the Revisions and History tabs. 

![Screenshot 2020-02-19 at 14 59 12](https://user-images.githubusercontent.com/4193672/74840008-eb546880-532e-11ea-8133-34c39c080b61.png)

**Comment by JohnPixle** [comment]
I think the Reset function does not register as a change. If you Reset a Style Kit and then close the editor, you dont get the "save changes" popup.

**Comment by mauryaratan** [comment]
Fixed in 485225721ad5e7b1c183610163ed1c8eadc5ff0a
