### ISSUE TITLE
Odd behavior with Export action at Theme Style Kits Table List 

### ISSUE THREAD

**Issue by lushkant** [mauryaratan/analogwp-templates#355]
It just sometimes returns the following even when the kit has data, this happens after you have edited or updated the kit or created one but has some styles.
> The template is empty.

**Comment by mauryaratan** [comment]
It was for a simple reason of Kit's post content is blank, in which Elementor considers it invalid. I've added `Analog\Elementor\Kit\Manager\get_kit_content()` to be used when creating a kit that fixes the issues.
