### ISSUE TITLE
Elementor's default kit should be pre-selected at settings if not GSK set

### ISSUE THREAD

**Issue by lushkant** [mauryaratan/analogwp-templates#357]
From now on, the Elementor’s default kit must be pre-selected in case there is not a GSK defined by the user. Hence, the dropdown must never show the “Select SK” option. Because this creates some conflicts.
![Screenshot 2020-02-21 at 19 30 15](https://user-images.githubusercontent.com/18240138/75057656-8ac85580-54ff-11ea-802c-767bc46f5b66.png)

**Comment by JohnPixle** [comment]
Yes @mauryaratan I think now that the Default Kit will ALWAYS apply on any page that does not use any of the other SKs, this dropdown at the settings must never remain blank (without a selection).

So, as a user, I should never be able to save the page with the "Select Style Kit" as a dropdown selection. Perhaps we should remove this placeholder text and have the "Default Kit" there by default.

Also I found out that even when this dropdown remains with the "select a SK" selected, then we have a strange behaviour as outlined in this video.
https://www.loom.com/share/80e36476e9be4d188c5dba2320371c1c
