### ISSUE TITLE
Update read more link at onboarding screen

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#361]
The read more link, we need to link it to this article: https://analogwp.com/style-kits-1-6-beta/

![Screenshot 2020-02-24 at 18 26 13](https://user-images.githubusercontent.com/4193672/75170743-3b6a6b00-5733-11ea-8022-2c204c30addf.png)

**Comment by mauryaratan** [comment]
@JohnPixle If we're going to use the same post for public release, is it really a good idea to have that post tagged as beta?
