### ISSUE TITLE
Remove "Edit with Elementor" link from Theme Style Kits page in dashboard

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#379]
We discussed this on Slack, just adding it here to make sure we dont miss it with the update.

![Screenshot 2020-04-22 at 16 09 25](https://user-images.githubusercontent.com/4193672/80013660-edc27280-84d7-11ea-8204-581a749b3ce8.png)

**Comment by mauryaratan** [comment]
Fixed in d6f9015289faf35698c6ee29012309f7baa1b6d3
