### ISSUE TITLE
Notifications issue with SK template library

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#463]
I think we have an issue with the placement here

![Screenshot_2020-12-07_at_22 51 29-1](https://user-images.githubusercontent.com/4193672/103529301-1899fe80-4e8e-11eb-927a-759fc0bb0088.png)

cc @gvgvgvijayan @mauryaratan

**Comment by gvgvgvijayan** [comment]
@JohnPixle The issue was already resolved and merged in the develop branch

https://github.com/analogwp/analogwp-templates/issues/460

**Comment by JohnPixle** [comment]
Thanks and sorry!
