### ISSUE TITLE
SK panel shortcuts are not working

### ISSUE THREAD

**Issue by lushkant** [mauryaratan/analogwp-templates#486]
Clicking on shortcut links to SK panels at Kit settings are failing and simply showing a blank page. Need to fix it asap.

**Comment by JohnPixle** [comment]
I think we have fixed this already, shall we close it?

**Comment by JohnPixle** [comment]
Just bringing this to the surface as recently discussed on slack. The links do not work, nor at the contextual menu, nor at the help links under the controls (container presets)


[Slack.](https://analogwp.slack.com/archives/CJ72D4S03/p1655473592692749)
