### ISSUE TITLE
Container Spacing presets

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#487]
As discussed in Slack, we can facilitate a new panel with the controls for padding and Elements gap.

I have worked on some mockups, ping me on slack if you need any clarifications @lushkant 
[Figma link.](https://www.figma.com/file/WE9qxn4dt8TEmHa7JIhNi6/Style-Kits-Remix?node-id=75%3A616)

![Container presets](https://user-images.githubusercontent.com/4193672/163838884-5f9244b1-07be-4644-8ed1-1e45b5acf03c.png)

**Comment by JohnPixle** [comment]
@lushkant I just realised that it is much helpful to be able to see the values of all presets at the same time, instead of using the popup. Can we make the transition to this please?
[Figma](https://www.figma.com/file/WE9qxn4dt8TEmHa7JIhNi6/Style-Kits-Remix?node-id=77%3A421)

![Screenshot 2022-04-19 at 11 05 14](https://user-images.githubusercontent.com/4193672/163955886-0de41da9-6d91-49cc-92f3-976e9e9538ea.png)

**Comment by lushkant** [comment]
Now included in Style Kits v1.9.0 experiments.
