### ISSUE TITLE
Rename label for sk classes

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#493]
For this label
<img width="286" alt="image" src="https://user-images.githubusercontent.com/4193672/167120861-c4dbdfe7-ffb7-4576-9b41-ee9173d25239.png">

Let's rename it to 
Background presets. _Edit in Style Kits_ (should take you to the SK bg classes panel)

_Edit in Style Kits_ sounds good and makes sense in general. Think we can use the same help text for the container padding presets as well? If you like it, add it please.

**Comment by JohnPixle** [comment]
I have a feeling that the label AND the help text will look weird 🤣

**Comment by lushkant** [comment]
yeah so I'm doing it accordingly, we can improvise it later when you test 👍
