### ISSUE TITLE
Introduce Style Kits Colors to Global Colors panel

### ISSUE THREAD

**Issue by lushkant** [mauryaratan/analogwp-templates#495]
Bring forth new color presets and custom preset options at the kit Global colors panel, for better.

Slack conversations - https://analogwp.slack.com/archives/CJ72D4S03/p1652346018216939
Figma link - https://www.figma.com/file/WE9qxn4dt8TEmHa7JIhNi6/Style-Kits-Remix?node-id=88%3A661

**Comment by JohnPixle** [comment]
As discussed in Slack, here is the updated UI.

On the left, you will see the color variable slugs I am suggesting. I would love to stay generic like sk-color-1 etc.
Here is a quick video as well: https://www.loom.com/share/a6443d91be9e4a8c8267b4270727d3e8

![Screenshot 2022-05-19 at 19 29 40](https://user-images.githubusercontent.com/4193672/169352859-c69d539f-282d-4e11-a9bf-6ef842d771f3.png)

**Comment by lushkant** [comment]
Revised in #498
