### ISSUE TITLE
Shadow presets + bg classes dropdown can become public

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#502]
Shadow presets and the SK background classes appear to be working fine, can we remove them from the experiments and have them in production?

**Comment by lushkant** [comment]
sure, I'll add them in this release.

**Comment by JohnPixle** [comment]
@lushkant You did not add those in production, right? I see they are still in experiments.

**Comment by lushkant** [comment]
They will be included in the release, since already implemented and ready, nothing breaking rn. And out of current PR subject.
