### ISSUE TITLE
Create Style variables for new app UI

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#512]
I have cleaned up the figma and organised the UI into 8 type styles and 10 colors. Let's make those variables and use them to redesign the library and overall within the app UI in version 2.

[FIgma file is here. ](https://www.figma.com/file/WE9qxn4dt8TEmHa7JIhNi6/Style-Kits-Remix?node-id=278%3A2104)
![SK App Styles](https://user-images.githubusercontent.com/4193672/174655143-84c40b16-4e79-46b0-a804-fbc9d959eff3.png)

Styling is not extremely important at this point, let's start building with these placeholders and since we have the variables handy we can update them (accent color / fonts etc).

This is needed to proceed with #511

**Comment by lushkant** [comment]
This is old now and is already being addressed in #511
