### ISSUE TITLE
Investigate performance issue

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#515]
Many times when I open the editor, I get a spinning circle at the toolbox sidebar. It usually gets to normal after several hard refreshes.

![Screenshot 2022-06-21 at 23 01 40](https://user-images.githubusercontent.com/4193672/174887613-987bd5e0-721c-433d-a388-17be192f16cf.png)

The page in case you want to check is [this](https://preview.analogwp.com/designsystem/patterns/heroes-page-titles/).
As discussed in Slack, here are the error messages:

![Screenshot 2022-06-21 at 22 57 09](https://user-images.githubusercontent.com/4193672/174887731-84a427d6-75b8-423b-80a6-0f322f44500c.png)

![Screenshot 2022-06-21 at 22 57 15](https://user-images.githubusercontent.com/4193672/174887742-68e9f088-64a7-416f-9713-c77237c57b3a.png)

Can you look into it so we can be sure it's nothing SK related?

**Comment by lushkant** [comment]
Not related to Style Kits 🙌

**Comment by mauryaratan** [comment]
For record, the 500 error seem to be coming from Elementor Pro's usage module.

**Comment by JohnPixle** [comment]
that's a relief, thanks!
