### ISSUE TITLE
Re-order sk experiments

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#516]
@lushkant It's not my fault man, you should have thought about that.

Let's put the **Style Kit Fonts** experiment under the **Style Kit Color palette**. Having the shadow between them does not make much sense.
![Screenshot 2022-06-22 at 17 17 16](https://user-images.githubusercontent.com/4193672/175052310-a9a4a440-206e-4c15-a0be-86947bbe6090.png)

**Comment by lushkant** [comment]
Not a valid issue sorry 🧐
