### ISSUE TITLE
New and Legacy Library Experiment

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#527]
We need to make the transition from the old library to the new one, in practical steps. I suggest:

- [x] Add an experiment to Style Kits Experiments, that makes the transition and pulls the new data into the gallery.
- [x] The old library with the existing content will be available only when the Library experiment is de-activated.

This is related to #511

**Comment by JohnPixle** [comment]
I think this is done almost, we had that in the earlier PR at play. We'll need to re-do it for the next version

**Comment by lushkant** [comment]
This is addressed in PR #550.
