### ISSUE TITLE
Accent colors retirement and fallback

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#528]
Regarding this, we should get rid of the Accent colors panel, it is just too confusing, and not so much of use now that we have the global SK colors. I think the best way would be to do the following:

If it's a new installation, we should simply hide the panel.
Existing installations, let's move it at the very bottom of the sidebar and add a "legacy" in the title.

![Screenshot 2022-09-30 at 23 36 36](https://user-images.githubusercontent.com/4193672/193352532-c441f9e2-7313-4f17-ad49-78844e6e7b34.png)

For new installations we might also need to remove it from the "Deactivate SK panels" tab in Settings

![Screenshot 2022-09-30 at 23 38 37](https://user-images.githubusercontent.com/4193672/193352755-6895fa3b-e734-4790-a509-88eab19d4bec.png)

Let me know if you have other ideas about this!

**Comment by lushkant** [comment]
Addressed in https://github.com/analogwp/analogwp-templates/issues/641
