### ISSUE TITLE
Revise & simplify Kit Settings

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#529]
![Screenshot 2022-07-01 at 00 36 03](https://user-images.githubusercontent.com/4193672/176782218-5c3bfb99-0809-40a9-af67-d536893051ec.png)

**Comment by JohnPixle** [comment]
Wehen we tackle this, we need to make sure that

- [x] Reset applies to containers 
- [x] Reset applies to global fonts and colors (both elementor's and SK)

**Comment by lushkant** [comment]
I have tested this and it works as expected already!
