### ISSUE TITLE
Replace Old docs links

### ISSUE THREAD

**Issue by mauryaratan** [mauryaratan/analogwp-templates#549]
John has started moving docs to the site. We should audit the docs, figure correct links and start replacing them in the plugin.

Alternatively, we can use HelpScout's redirects to redirect them on our website https://secure.helpscout.net/settings/docs/redirects/5c5ee14e042863543cccc74c/

**Comment by JohnPixle** [comment]
I'm planning to do that for all links in the app, I'll follow up when ready.

**Comment by JohnPixle** [comment]
@lushkant whenever you have the chance, can you please do a search across the code and share all the link urls pointing to the old docs?
I will then provide a list with the updated urls on the new docs.

**Comment by mauryaratan** [comment]
@JohnPixle here you go:

1. https://docs.analogwp.com/article/575-text-and-heading-sizes
2. https://docs.analogwp.com/article/544-remove-styling-from-typographic-elements
3. https://docs.analogwp.com/article/608-sk-select-template-import
4. https://docs.analogwp.com/article/590-style-kit-library
5. https://docs.analogwp.com
6. https://docs.analogwp.com/article/661-wizard-setup
8. https://docs.analogwp.com/article/574-working-with-colours,
9. https://docs.analogwp.com/article/657-style-kit-color-pallete
10. https://docs.analogwp.com/article/575-text-and-heading-sizes
12. https://docs.analogwp.com/article/655-container-presets
13. https://docs.analogwp.com/article/587-outer-section-padding
14. https://docs.analogwp.com/article/588-working-with-column-gaps
15. https://docs.analogwp.com/article/586-button-styles-and-sizes
16. https://docs.analogwp.com/article/660-new-style-kits-panel
17. https://docs.analogwp.com/article/658-style-kits-fonts
18. https://docs.analogwp.com/article/659-local-style-kits
19. https://docs.analogwp.com/article/548-beta-features
20. https://docs.analogwp.com/article/637-template-import-method
22. https://docs.analogwp.com/article/547-what-data-is-tracked-by-the-plugin

**Comment by JohnPixle** [comment]
Thanks man!

**Comment by JohnPixle** [comment]
I have updated the list with the new docs links.
In the first row is the old link, and in the second row is the new one.

Also, it would not hurt to do a search for old docs in the SK PRO codebase.

- [x] https://docs.analogwp.com/article/575-text-and-heading-sizes
https://analogwp.com/docs/typographic-sizes/

- [x] https://docs.analogwp.com/article/544-remove-styling-from-typographic-elements
☝🏻 This one is too old and removed, I don’t think it is somewhere inside the app anymore.

- [x] https://docs.analogwp.com/article/608-sk-select-template-import
https://analogwp.com/docs/default-template-import-method/

- [x] https://docs.analogwp.com/article/590-style-kit-library
https://analogwp.com/docs/importing-global-style-presets/

- [x] https://docs.analogwp.com/
https://analogwp.com/docs/

- [x] https://docs.analogwp.com/article/661-wizard-setup
https://analogwp.com/docs/the-setup-wizard/

- [x] https://docs.analogwp.com/article/574-working-with-colours
https://analogwp.com/docs/style-kit-global-colors/

- [x] https://docs.analogwp.com/article/657-style-kit-color-pallete
https://analogwp.com/docs/style-kit-global-colors/

- [x] https://docs.analogwp.com/article/575-text-and-heading-sizes
https://analogwp.com/docs/typographic-sizes/

- [x] https://docs.analogwp.com/article/655-container-presets
https://analogwp.com/docs/container-spacing/

- [x] https://docs.analogwp.com/article/587-outer-section-padding
https://analogwp.com/docs/outer-section-padding/

- [x] https://docs.analogwp.com/article/588-working-with-column-gaps
https://analogwp.com/docs/column-gaps/

- [x] https://docs.analogwp.com/article/586-button-styles-and-sizes
https://analogwp.com/docs/button-sizes/

- [x] https://docs.analogwp.com/article/660-new-style-kits-panel
https://analogwp.com/docs/overriding-global-style-kit/
Where is this one mentioned inside the app? 🤔 

- [x] https://docs.analogwp.com/article/658-style-kits-fonts
https://analogwp.com/docs/style-kit-global-fonts/

- [x] https://docs.analogwp.com/article/659-local-style-kits
https://analogwp.com/docs/local-style-kits/

- [x] https://docs.analogwp.com/article/548-beta-features
https://analogwp.com/docs/style-kits-experiments/

- [x] https://docs.analogwp.com/article/637-template-import-method
https://analogwp.com/docs/default-template-import-method/

- [x] https://docs.analogwp.com/article/547-what-data-is-tracked-by-the-plugin
https://analogwp.com/docs/what-usage-data-is-tracked-by-style-kits/
☝🏻 We need to talk about this one, ping me in Slack.

**Comment by JohnPixle** [comment]
Also, I noticed that the "enable SVG uploads" points to the Template import method doc: https://docs.analogwp.com/article/608-sk-select-template-import 

Probably my mistake for now creating a new doc.

![Screenshot 2022-12-14 at 8 49 07 PM](https://user-images.githubusercontent.com/4193672/207685893-d27a7ba3-6cb5-4fca-a09a-d395511db5ef.png)

It should point to this one which I just created:
 
- [x] https://analogwp.com/docs/enable-svg-imports-in-patterns
- [x] Since we are here, in settings, let's also rename it **Enable SVG imports** instead of **Enable SVG uploads** please 👍🏻
