### ISSUE TITLE
Issue when switching tabs in library

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#567]
Here's a quick video about the issue. 
https://www.loom.com/share/488cceabf2f041efa6299eb2a361f515

**Comment by JohnPixle** [comment]
@lushkant shall I close this? i think you already addressed this one.

**Comment by lushkant** [comment]
> @lushkant shall I close this? i think you already addressed this one.

Yes, I have, though it's in #550 PR which hasn't been merged yet. When it does it will automatically close this issue 🚀

**Comment by lushkant** [comment]
This has already been addressed in PR #550, and to eliminate any confusion let's close this.
