### ISSUE TITLE
Use placeholder graphic when Thumbnails are loading

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#575]
We used to have that placeholder svg image while the templates were loading. Since there will now be a bunch of patterns now, it would make sense to have it appear while the image loads. Currently when you scroll down the page the boxes appear white.

Here is the svg placeholder @lushkant 

![placeholder](https://user-images.githubusercontent.com/4193672/190602958-3d78e671-4013-4e73-b1c9-856a510bc551.svg)

**Comment by lushkant** [comment]
As discussed, this is available and working in PR #550!
