### ISSUE TITLE
Final fixes before wrapping up 1.9.5

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#578]
Hey, I am creating this issue here which contains several minor things before the release.

### SK Experiments area:
- [x] **Let's remove the container spacing from the experiments.** IF the Elementor containers experiment is enabled, then our Container Spacing feature should be active.
- [x] Let's do the same for **SK colors and fonts.** This is not related to any Elementor Experiment, so let's release both of these by default.

This will leave us with only one SK experiment: The Container-based library
- [x] Change Experiment title to: Container-based library
- [x] Revise the description: Get early access to the upcoming container-based library of Patterns. You need to have the Containers experiment activated in Elementor, to test the new library.

### Library tweaks:

- [x] Let's set the color of the "favorite" triangle to the dark color (similar to the PRO label). This way the yellow star will look good when the user favorites a pattern. 

![Screenshot 2022-09-20 at 18 40 52](https://user-images.githubusercontent.com/4193672/191303056-f42be5bc-e024-4628-9501-7d7222cd9a79.png)

- [x] <strike>If I disable the SK PRO version, I can import the PRO assets just fine :P. When in Free version instead of the "Import button" it should say "Go Pro" and link to the SK Pricing page.</strike>

![Screenshot 2022-09-20 at 18 46 58](https://user-images.githubusercontent.com/4193672/191304777-7330535f-40aa-4597-9273-10be54cfbdcd.png)

- [x] <strike>Add a toggle to "Hide PRO Patterns" as in the mockup below</strike>

![Screenshot 2022-09-20 at 18 55 43](https://user-images.githubusercontent.com/4193672/191306553-e1dab0ea-57ec-48b0-91cc-ebfa31bdae76.png)

- [x] How about moving the search field to the sidebar (as in the mockup above) instead of it's current position? Because we will need to accomodate the PRO banner as well above the patterns. Additionally, such a long search input does not make sense.

![Screenshot 2022-09-20 at 19 02 24](https://user-images.githubusercontent.com/4193672/191308243-e9bb1d74-9083-4950-8ac2-a077ba3dbf5c.png)

### Other UI Tweaks

- [x] In Free version of SK, the Elementor Forms panel has an outdated title. Let's rename it from "Forms (Extended)" to "Elementor Forms"

- [x] Please take a look at this as well and let me know if it's possible and easy to squeeze in the current milestone. #577 

CC @lushkant @mauryaratan

**Comment by mauryaratan** [comment]
@lushkant can you please check/uncheck the todos here based on their status? Strike through for invalid items.
