### ISSUE TITLE
When Pro license is activated, let's hide the "PRO" label on the PRO patterns

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#583]
It gets a bit overwhelming to have the PRO labels when the user is a PRO client, can we remove them when the license in activated? Let's do the same for PRO Style Kits as well.

![Screenshot 2022-10-03 at 19 12 55](https://user-images.githubusercontent.com/4193672/193627004-939c6e23-05cf-465b-b8ca-1fc9caea9d43.png)

**Comment by lushkant** [comment]
As discussed, this is a bad idea let's close it.
