### ISSUE TITLE
Re-renaming the labels of SK fonts and colors

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#592]
Here are the updated labels. Ping me in Slack for clarifications! 
Some of the variables will remain blank, because they are not being used by our patterns. 

### Colors

Number | Label  | Color Value |
| -------------| ------------- | ------------- |
1 | Site background  | `#FFFFFF` |
2 | Light background  | `#F4F4F4`  |
3 | Dark background  | `#171720`  |
4 | Background 4  | **leave blank**  |
5 | Accent 1  | `#413EC5`  |
6 | Accent 2  | leave blank  |
7 | Accent 3  | leave blank  |
8 | Accent 4  | leave blank  |
9 | Titles  | `#1B1B1D`  |
10 | Normal text  | `#1B1B1D`  |
11 | Secondary text  | `#707071`  |
12 | Inverted text  | `#FFFFFF`  |
13 | Border  | `#0000001A`  |
14 | Color Style 14  | **leave blank**  |
15 | Color Style 15 | **leave blank**  |
16 | Color Style 16  | **leave blank**  |

### SK Fonts

For SK Fonts we will only define Sizes, the font families should be set to default.

Number | Label  | Font family | Font Size
| -------------| ------------- | ------------- |------------- |
1 | Display title  | Default  | 5 em |
2 | Title 1  | Default  | 4 em |
3 | Title 2  | Default  | 3 em |
4 | Title 3  | Default  | 2 em |
5 | Title 4  | Default  | 1,5 em |
6 | Title 5  | Default  | 1,2 em |
7 | Title 6  | Default  | 1 em |
8 | Overline / Subheader  | Default  | 0.8 em |
9 | Display text  | Default  | 2 em |
10 | Large text  | Default  | 1,5 em |
11 | Normal text  | Default  | 1 em |
12 | Small text  | Default  | 0,95 em |
13 | Caption  | Default  | 0,8 em |
14 | Button text  | Default  | 1 em |
15 | Form label | Default  | 1 em |
16 | Font Style 16  | **leave blank**  | **leave blank** |

### Background Color Classes

Turns out we will need to set defaults for these as well. Just in case any patterns with dark / light presets are imported.

Light BG | Color hex |
| -------------| ------------- | 
Background color  | #F4F4F4 |
Text color  | leave it blank, it will use body text color |
Headings color  | leave it blank, it will use body text color  |

Dark BG | Color hex |
| -------------| ------------- | 
Background color  | #171720 |
Text color  | #FFFFFF  |
Headings color  | #FFFFFF  |

### Container Spacing Presets

Lastly, let's change just the default labels for Container padding presets (to give a reference to the users about how these are used in patterns)

Current | New |
| -------------| ------------- | 
Padding 1  | XXL - Hero Section |
Padding 2  | XL - Primary Section |
Padding 3  | Large - Box |
Padding 4  | Medium - Box |
Padding 5  | Small - Box |

Thanks mate!

**Comment by lushkant** [comment]
@JohnPixle no hurries lemme know when this is done 🚀
