### ISSUE TITLE
Fix Pattern and SK Grids in the library

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#593]
Can we work a bit on the patterns grid? With the latest tweaks, the whole content seems to be restricted in width, and the pattern boxes appear very small. Can we have some more fluid control over here? Perhaps the whole content should extend to full-width, and have more responsive control with the thumbnails?

I was thinking about a behaviour like this (number of items per row changes based on viewport)
https://codepen.io/helloandyb/pen/XejqEE

![Screenshot 2022-10-07 at 14 33 14](https://user-images.githubusercontent.com/4193672/194544012-c4555578-28db-40a7-b3bb-9701f3b5f062.png)

For the STyle Kit Perhaps 3 SKs per row would help (32% each), currently the boxes look too small 😬 

![Screenshot 2022-10-07 at 14 37 24](https://user-images.githubusercontent.com/4193672/194544417-6a9873bc-0d86-4fa9-ad07-7bde4e1b8adf.png)

Let me know if you need any clarifications!

**Comment by lushkant** [comment]
@JohnPixle this is deployed at play, please check it out and let me know what else can we improve?
