### ISSUE TITLE
🆘 Improve Style kit switching inside the editor

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#605]
This is related to the Slack discussion, and this [loom video](https://www.loom.com/share/576b9daa534d477283509d761abf965e). 

Ram [has suggested](https://analogwp.slack.com/archives/CJ72D4S03/p1665999327101209) that: 

> instead of giving them a prompt to reload the settings; lets trigger settings save and automatically reload the page to avoid any possibility of confusion

Which is good by me.

However, if we can switch the kits inside the editor without a reload, it is also fine.
Let me know for any clarifications.

**Comment by JohnPixle** [comment]
@lushkant  Here are the final tweaks we need to do at the Style Kits panel, based on our last updates on Slack.

- [x] **Change panel text.**
Let's change the text to: `Select a different Style Kit to be applied on this page. The page will reload after your selection. Learn more.` It would be great to have this as normal instead of italic. 

- [x] **The tooltip on hover** should say `This will override your site's Global Style Kit for this page.`

- [x] **Add the toast after reloading the Page.**
Text should say `All good. The new Style Kit has been applied on this page. ` Since now we will be taking them inside the theme styles after refresh, it would be good to have two links in the toast, as in the screenshot. So, apart from "Switch Style Kit" (which will open the SK panel), let's add another one for "Back to Editor".

![SK panel rev](https://user-images.githubusercontent.com/4193672/196879630-f2696b5f-b35f-4f41-843b-3cc85ef41eaf.png)

**Comment by JohnPixle** [comment]
I think this can be closed no? We addressed it in the last update haven't we?

**Comment by lushkant** [comment]
Yes we did, and closing it.
