### ISSUE TITLE
Regenerate Styles

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#611]
In order to avoid CSS getting messed up, we better force the regeneration of Styles in some cases:

- [x] **On Plugin update.** hen the plugin is updated, the Styles should be regenerated.
- [x] **After setting a Global Style Kit.** I made some tests, and looks like we should do this as well. So, after applying a new Global Style Kit, let's regenerate the styles as well.

### Bonus task:
- [x] When users apply a new style kit, it is always handy to give them a link to quickly view the frontend. Let's add a "View site" link at the end of the notification, that **will open a new tab and load the homepage**. Elementor does something similar when users import a Site Kit.

![Screenshot 2022-10-20 at 09 16 05](https://user-images.githubusercontent.com/4193672/196870710-8a7c1469-c253-49bc-837a-dba97cfa7452.png)

**Comment by JohnPixle** [comment]
@lushkant hey just checking-in on this one. Do we have this ready? Need any help from me?

**Comment by lushkant** [comment]
> @lushkant hey just checking-in on this one. Do we have this ready? Need any help from me?

Getting it ready rn.
