### ISSUE TITLE
Issue with default spacing preset of containers

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#616]
By default, Elementor sets a default 10px padding to all containers. 

![Screenshot 2022-10-31 at 18 56 55](https://user-images.githubusercontent.com/4193672/199064939-db515874-3960-4d1a-a2fe-1bc179adf732.png)

Now, our "default" spacing preset should output the default value, whatever it is. It works well if I add a custom value in Layout Settings > Container Spacing, but when there is no value, it does not output the default 10px value as it should.

Here is a quick video outlining the issue: https://www.loom.com/share/a0529cbb71f14d49b430411342f41965

I did try that on the preview site as well, there the default value is showing up in the frontend but not in the editor. Weird stuff. Let's see if we can tackle this one.

**Comment by JohnPixle** [comment]
@lushkant what about this one? As mentioned in Slack this appears to be fixed in the latest version of Elementor, but there must had been an issue earlier. Shall we investigate or leave as is?

**Comment by JohnPixle** [comment]
@lushkant The issue is there unfortunately

Edit this page: https://chunkyscissors.s1-tastewp.com/default-container-padding

Site name: Chunky Scissors
URL: https://chunkyscissors.s1-tastewp.com
Username: pixle
Password: uxXj13ewnFc

**Comment by lushkant** [comment]
As discussed, let's close this issue!
