### ISSUE TITLE
Container spacing 6-8 missing from PRO version

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#625]
I think there is something wrong with the Spacing Presets in the PRO version 😭

### This is Style Kits Free:

5 controls are populated, 6-8 are blank (all correct)
![Screenshot 2022-11-08 at 8 25 06 PM](https://user-images.githubusercontent.com/4193672/200645559-ee878cd0-ede3-49b1-98c2-4a45cc63fd4f.png)

### This is Style Kits PRO:

6-8 are missing.

![Screenshot 2022-11-08 at 8 26 39 PM](https://user-images.githubusercontent.com/4193672/200645763-bd09474d-c143-48b7-9a45-9751ed2bf340.png)

**Comment by JohnPixle** [comment]
Hm... This seems to be happening only at the analogWP site, I tried on play and another one and it works as expected, the 6-8 presets are there... Maybe a false alarm but let's give it a look just to be sure...

**Comment by lushkant** [comment]
Looks like a false alarm to me as well, as the everything else is right. I just reset the spacing presets to defaults and then updated back to what you had earlier which brought back the missing presets.

Let me know if there's anything else.
