### ISSUE TITLE
library patterns not respecting plugin requirements

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#636]
If EL PRO is missing from the user's site and a pattern is marked as it requires EL PRO, then **prevent** the pattern from being imported.

![Screenshot 2022-12-01 at 12 29 19 PM](https://user-images.githubusercontent.com/4193672/205031720-59a163db-dbf3-47d3-85c6-bd0b94d84bb2.png)

**Comment by lushkant** [comment]
Assets and mockups

![Screenshot 2022-12-01 at 12 57 57 PM](https://user-images.githubusercontent.com/18240138/205035933-c28dce61-b76e-40c0-8faa-ee206b9d5be7.png)

![elementor-logo](https://user-images.githubusercontent.com/18240138/205035923-d5e6fadc-1358-43b4-bb64-12fac9aa06bf.svg)

**Comment by JohnPixle** [comment]
As a quick update, I have completed the backend work for each pattern, and have marked them appropriately based on the plugin requirement.

**Comment by JohnPixle** [comment]
@lushkant I don't think this is working either man. Tried with Elementor PRO de-activated and the Patterns are still displaying without the overlay. Can you double check?

**Comment by lushkant** [comment]
> @lushkant I don't think this is working either man. Tried with Elementor PRO de-activated and the Patterns are still displaying without the overlay. Can you double check?

Hey yes, it won't as the code dependent wasn't yet deployed on analogwp.com and preview site. It was under PRs and I just published it. Though we will still need to update the patterns one more time to sync the data.
