### ISSUE TITLE
Rollback feature is missing from Settings?

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#639]
I think there is an issue with the rollback feature that was until recently under Settings > version control?

![file-0Bd39JQGeN](https://user-images.githubusercontent.com/4193672/207806026-c2a5bcb0-1aae-4f61-ab32-939d35faabeb.png)

From this panel, what needed to have been removed was the Beta Features section (which has been replaced with the experiments tab) and not the rollback section. Am I missing something?

[Link to settings.](https://analogwp.com/wp/wp-admin/admin.php?page=ang-settings&tab=version-control)

This is how it looks now

![Screenshot 2022-12-15 at 10 08 40 AM](https://user-images.githubusercontent.com/4193672/207806293-55cb2a9d-6857-4cd0-b63b-b64c90c3f1c2.png)

**Comment by lushkant** [comment]
This was not visible at our sites because of updates being disabled.
