### ISSUE TITLE
Legacy features

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#641]
With the introduction of Containers, our Column Gaos and Outer Section Padding panels are becoming redundant. Same applies for Accent Colors panel, which does not make much sense anymore, it was there before Elementor’s Theme Styles.

What we want to do is to discourage users from using them, and in the long-term retire them.

However, during this transition period, many users will still use sections in their websites, so we need to keep the panels (and their data) available.

I suggest that we do the following:

### 1. Separate the three tools in a separate section of the SK panel.

This way users will have a clear understanding that these are legacy features.  I have created two mockup suggestions for this, based on what is technically possible.

![Screenshot 2022-12-16 at 2 18 06 PM](https://user-images.githubusercontent.com/4193672/208097227-0342035e-e916-4eec-ac40-72e41e7690c3.png)

### 2. Add an option to settings to Hide the Legacy features.

This way users who don’t use them anymore can hide them from the UI completely.

![Screenshot 2022-12-16 at 2 10 55 PM](https://user-images.githubusercontent.com/4193672/208097241-54a1b38b-5b06-4056-9e45-3af8eeef5fb6.png)

**Comment by JohnPixle** [comment]
For the Accent colors specifically, I would suggest that **in every new SK install**, we hide this control completely from now on. However Column gaps and OSP might still be needed for some time, so let's keep them.

**Comment by JohnPixle** [comment]
@lushkant 

- [x] In Settings, the link for the legacy issues is wrong, it should be https://analogwp.com/docs/what-are-legacy-features/
![Screenshot 2023-01-19 at 4 06 02 PM](https://user-images.githubusercontent.com/4193672/213464138-77326d3b-734e-4df2-8295-7264228ec250.png)

**Comment by lushkant** [comment]
oh yeah thanks for that one and done!

> @lushkant
> 
> * [x]  In Settings, the link for the legacy issues is wrong, it should be https://analogwp.com/docs/what-are-legacy-features/
>   ![Screenshot 2023-01-19 at 4 06 02 PM](https://user-images.githubusercontent.com/4193672/213464138-77326d3b-734e-4df2-8295-7264228ec250.png)
