### ISSUE TITLE
Set up instawp demo

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#646]
I am adding this one in this repository for better visibility.

As we had discussed in Slack, we need to establish the following flow:

When users click on the insta link:
https://app.instawp.io/launch?t=style-kits

they should land to the "welcome" template that already exists in the Elementor library. 
I have updated that template with the latest videos.

![Screenshot 2023-01-11 at 7 55 51 PM](https://user-images.githubusercontent.com/4193672/211883668-fd2d7d63-805a-482e-863f-68a0834540f3.png)

I don't recall where we left this tbh. I think some action is required by your side, in order for the users to land to that template instead of the WP dashboard.

Let me know if you need any clarifications. Everything is ready, we are just missing this final step in order to share the link.

cc @mauryaratan

**Comment by JohnPixle** [comment]
@mauryaratan Take a look at that when you can. Everything is ready to go, except the  redirect hack to take the users on a template

**Comment by lushkant** [comment]
@JohnPixle this is done and deployed, although there is a caveat. Since we can't anymore do the wp-cli commands in our current plan at instawp, what we did was added a custom plugin which redirects from dashboard to our welcome page url. It's a hack but it works. 

Try it out yourself - https://app.instawp.io/launch?t=style-kits

**Comment by JohnPixle** [comment]
@lushkant Thanks for taking care of it. Looks good but the thing is that now it redirects to the front-end of the page
: https://style-kits.instawp.xyz/?elementor_library=sk-onboarding

What we want is to open this page in the elementor editor, not the front-end: https://style-kits.instawp.xyz/wp-admin/post.php?post=11&action=elementor (in order for users to be able to directly insert patterns).

Possible? If not it's not a big deal, I will adjust the template.

**Comment by lushkant** [comment]
> @lushkant Thanks for taking care of it. Looks good but the thing is that now it redirects to the front-end of the page
> : https://style-kits.instawp.xyz/?elementor_library=sk-onboarding
> 
> What we want is to open this page in the elementor editor, not the front-end: https://style-kits.instawp.xyz/wp-admin/post.php?post=11&action=elementor (in order for users to be able to directly insert patterns).
> 
> Possible? If not it's not a big deal, I will adjust the template.

We can definitely do so, ill just apply that.

**Comment by lushkant** [comment]
@JohnPixle I have applied that, but remember that the target is set to open a post by the slug of `sk-onboarding` from the Elementor template library, so please don't change the slug from the main instawp site for the welcome page or if you do so let me know so that I can update the same in plugin.

**Comment by JohnPixle** [comment]
Thanks, works fine. Closing this issue 👍🏻
