### ISSUE TITLE
Import Starter Kit

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#652]
This idea is about offering an option to the users to start with a complete Starter Kit with a bunch of them-builder templates pre-packaged. Since in our library we only offer patterns, the Site Kit import will allow users to have options for Theme Builder templates. 

Here is the current Starter Kit Demo.

Workflow:

For now, let's go simple. In SK Settings page, we add a button to Import Starter Kit.

When users click the button, they go directly to the native elementor import wizard. We will provide the Kit Zip behind the scenes, so the user will not need to import a zip.

![Screenshot 2023-03-31 at 11 45 35 AM](https://user-images.githubusercontent.com/4193672/229074391-804e2f5b-e19b-4b22-b5a5-9b051486ed5a.png)

### Important!
The flow works well, but after the import is complete, we need to force-apply the Global Style Kit Selection in order for the styles to be applied correctly.

![Screenshot 2023-03-31 at 11 57 17 AM](https://user-images.githubusercontent.com/4193672/229075360-0052dc92-0da7-459e-8904-457326753c64.png)

Below is the kit I have worked on so far. You can use this one. Make sure you have enabled woocommerce at the site you will import to.

[Pulse Starter Kit.zip](https://github.com/analogwp/analogwp-templates/files/11120051/Pulse.Starter.Kit.zip)

[Video](https://www.loom.com/share/68848b0c6bc046e29f2401a0c9cf0cc7)

cc @lushkant @mauryaratan

**Comment by JohnPixle** [comment]
After the Slack Discussions, let's stick to a simple solution. [FIGMA](https://www.figma.com/file/WE9qxn4dt8TEmHa7JIhNi6/Style-Kits-Remix?node-id=1077%3A2509&t=f57gUYiUzPeRgNxq-1).

We just offer to download ZIPs and the user can import them manually to their website using the native flow.

![Screenshot 2023-04-11 at 8 13 16 PM](https://user-images.githubusercontent.com/4193672/231239180-eaf1782e-d9c7-4e72-b1f8-73baeade7c7b.png)


I will need to be able to upload the zips somewhere, and I need to be independent from you guys for when I want to update the files.Probably somewhere at analogwp.com ?

**Comment by lushkant** [comment]
> After the Slack Discussions, let's stick to a simple solution. [FIGMA](https://www.figma.com/file/WE9qxn4dt8TEmHa7JIhNi6/Style-Kits-Remix?node-id=1077%3A2509&t=f57gUYiUzPeRgNxq-1).
> 
> We just offer to download ZIPs and the user can import them manually to their website using the native flow.
> 
> ![Screenshot 2023-04-11 at 8 13 16 PM](https://user-images.githubusercontent.com/4193672/231239180-eaf1782e-d9c7-4e72-b1f8-73baeade7c7b.png)
> 
> I will need to be able to upload the zips somewhere, and I need to be independent from you guys for when I want to update the files.Probably somewhere at analogwp.com ?

Working on this and yes you can upload it at analogwp.com preferably in media files.

**Comment by lushkant** [comment]
@JohnPixle will also need a link for that Learn more button up top.

**Comment by JohnPixle** [comment]
@lushkant The learn more link will be: https://analogwp.com/docs/pulse-starter-kit/

**Comment by JohnPixle** [comment]
This works fine @lushkant thanks for the effort here. 
I have also optimised the ZIP and it's more lightweight.

3 tiny things:

- [x]  **After clicking the download button for ZIP**, possible to show a notification to the user with a link to the [Site Kit Import Page](https://play.analogwp.com/wp-admin/admin.php?page=elementor-tools#tab-import-export-kit)?

![Screenshot 2023-04-14 at 8 13 03 PM](https://user-images.githubusercontent.com/4193672/232118572-d3a8d21f-4244-434f-baf6-e572c1789bbd.png)

- [x] **If there is NOT a PRO file defined at Analog website, then the PRO section must not be visible.** I have removed the row from SK PRO at the site, but the PRO section still remains. Possible to have it off until I create a row?

![Screenshot 2023-04-14 at 8 46 43 PM](https://user-images.githubusercontent.com/4193672/232119368-183bb560-8917-4772-b4da-969a10240af8.png)

- [x] **Remember to set the right link to the "Read More".** It should go to https://analogwp.com/docs/pulse-starter-kit/


![Screenshot 2023-04-14 at 8 46 59 PM](https://user-images.githubusercontent.com/4193672/232119565-cfdb9636-6d26-4f2c-91d2-e3870eceee58.png)


- [x] **I tried to update the text,** but I did not see it changed in Settings. Does it need some time to sync?

![Screenshot 2023-04-14 at 8 50 11 PM](https://user-images.githubusercontent.com/4193672/232120091-791fd475-8167-4f78-92ac-e6b9fd02f186.png)

- [x] Lastly, let's remove the 1px solid border from the thumbnails at `.ang .ang-starter-kits-list img`
