### ISSUE TITLE
Button Sizes Support

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#668]
In latest version of Elementor, they have dropped completely the Button Sizes.
We need to do two things:

- [x]  When latest elementor version is detected (where button sizes are removed), we need to put the button sizes panel in the Legacy panel in Style Kits sidebar.

- [x] We need to make sure that the button sizes will still work for old instances.
 
 
 @lushkant Let me know if you need  any further help on that!

**Comment by lushkant** [comment]
Completed in #670
