### ISSUE TITLE
Error message with Elementor 3.18

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#669]
A user reported this in Support, can you take a look into it @lushkant ?:

Any sites with StyleKit installed causes this error when updating Elementor to 3.18: Elementor\Core\Kits\Documents\

Kit::handle_control_position: Cannot add a control outside of a section (use `start_controls_section`). The site is broken.

**Comment by lushkant** [comment]
This was addressed previously.
