### ISSUE TITLE
Button Sizes

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#677]
@lushkant I saw the solution for button sizes that you shared last night. It works ✅ 

Let's just make sure we add it in the list above, it looks weird where it is now with that extra border. Ideally we can have it under the Background color classes
<img width="300" alt="Screenshot 2024-12-05 at 10 05 02 PM" src="https://github.com/user-attachments/assets/bfe5443c-1249-4a6a-8d81-74956ffe29f9">

Also, we must do the same thing with the Typographic Sizes. they must have removed those also.
Here is an image of our related settings in SK. Let me know if it's possible, I can create a new issue.
<img width="280" alt="Screenshot 2024-12-05 at 10 11 02 PM" src="https://github.com/user-attachments/assets/78a43b8a-8714-408c-bb75-bd557f30623b">

**Comment by lushkant** [comment]
Fixed in #678
