### ISSUE TITLE
Colors Integration

### ISSUE THREAD

**Issue by mauryaratan** [mauryaratan/analogwp-templates#84]
Add global color setting in Page Styles, ideally as follows:

- 8 Predefined colors (we should avoid dynamically added settings fields here for the sake of consistencies
- Each color group should offer two fields:
  - Label
  - Color
- With 8 colors in place, each element should have a dropdown of these color names. When in effect this setting would add a class on the element which will apply the global color set in page styles.

Links:
- [Figma design](https://www.figma.com/file/WewTsQAjGvzRQahddcH0KK6m/Product-UI?node-id=309%3A2396).
- More details on [Notion](https://www.notion.so/analogwp/Color-Controls-in-Style-Kits-09b63e0064794b30a91553e7e23c6310).

**Comment by JohnPixle** [comment]
Is this the right issue to post?
Here is the Notion link
https://www.notion.so/analogwp/Color-Controls-in-Style-Kits-09b63e0064794b30a91553e7e23c6310
