### ISSUE TITLE
Re-order sizes panels

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#94]
What you think about moving Text sizes under body typography

And headings sizes under heading sizes? 

It might be a good idea or not. Perhaps it is better to keep the two size tabs where they are now... lets talk.

**Comment by mauryaratan** [comment]
I think they're at the right place @JohnPixle having their own sections. Makes scanning and searching through an easy task. In case you have got a different opinion, feel free to open this.
