### ISSUE TITLE
Empty Style Kit export isn't throwing an error as expected

### ISSUE THREAD

**Issue by lushkant** [mauryaratan/analogwp-templates#97]
When exporting an empty Style Kit instead of throwing an error it gives this 
`{"success":true}`

It's being caused in function `handle_style_kit_export()` at `class-tools.php:355`

https://github.com/mauryaratan/analogwp-templates/blob/56f281b52c8c7e432da021eddf00b8e4e5ae440f/inc/elementor/class-tools.php#L353-L355

There is no conditional check following up for this one when there is a wp_error `wp_send_json_success();`

Also the error throwing part can be personalized even further for users with this one right here - https://github.com/LucaRosaldi/wpfn-notifications

**Comment by mauryaratan** [comment]
Fixed in d43fe8eca4de64d87251e3c088c728eca28cdcfc.
