### ISSUE TITLE
Reverse the order of labels in Sizes panels

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#98]
I was thinking it would make sense to have the labels in reverse order, like we have in the headings panel:

- H1
- H2
- H3
etc...

In a similar way we can go from bigger size to the smaller instead of how we do it now.

I think we must follow the same logic in both **Headings sizes** and **Text sizes**

![Screenshot 2019-05-19 at 12 21 44](https://user-images.githubusercontent.com/4193672/57980208-c8f48e00-7a30-11e9-9a5f-4c064e2d4f49.png)

**Comment by mauryaratan** [comment]
I feel this is unnecessary. Let's not refactor things for the sake of refactoring.

This is a common pattern:
- Small > Medium > Large
- Narrow > Extended > Wide

But of course, for headings, we go incrementally. Let me know your thoughts @JohnPixle.

**Comment by JohnPixle** [comment]
I do not disagree, and i dont think this is simply for the sake of refactoring.

I am talking for Text and heading sizes. For Headings we go 

h1,h2,h3.... WHich is from bigger to smaller.
I found myself many times to follow the same hierarchy n the sizes tabs by mistake. If you do this in an actual workflow, you will see how it kicks.

What I am saying is to simply go from bigger to smaller there as well.
